# Generated by Django 4.2.14 on 2024-08-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cns_website", "0003_alter_badge_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="A photo of the user",
                null=True,
                upload_to="users/",
            ),
        ),
    ]
