# Generated by Django 5.0.7 on 2024-07-26 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField()),
                ("location", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="events/")),
            ],
        ),
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=30)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="officers/")),
                ("sort_order", models.IntegerField(default=0)),
            ],
        ),
    ]
