# Generated by Django 4.2.14 on 2024-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="color",
            field=models.CharField(
                choices=[
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("1", "2"),
                    ("gray-dark", "Dark Gray"),
                ],
                default="blue",
                help_text="Badge color",
                max_length=16,
            ),
        ),
    ]
