# Generated by Django 4.2.14 on 2024-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="officer",
            name="image",
            field=models.ImageField(blank=True, upload_to="officers/"),
        ),
    ]
