# Generated by Django 4.2.14 on 2024-07-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0002_alter_event_image_alter_officer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officer",
            name="name",
        ),
        migrations.AddField(
            model_name="officer",
            name="first_name",
            field=models.CharField(
                default="First", help_text="First name", max_length=30
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="officer",
            name="last_name",
            field=models.CharField(
                default="Last", help_text="Last name", max_length=30
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="officer",
            name="year",
            field=models.IntegerField(
                default=2024, help_text="The year this officer was elected"
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="bio",
            field=models.TextField(
                help_text="Officer's biography. Markdown is supported."
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="image",
            field=models.ImageField(
                blank=True, help_text="A photo of the officer", upload_to="officers/"
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="position",
            field=models.CharField(help_text="Position", max_length=30),
        ),
        migrations.AlterField(
            model_name="officer",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Optional sort order of officer"
            ),
        ),
    ]
