# Generated by Django 4.2.14 on 2024-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0002_badge_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("indigo", "Indigo"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                    ("black", "Black"),
                    ("white", "White"),
                    ("gray", "Gray"),
                    ("gray-dark", "Dark Gray"),
                ],
                default="blue",
                help_text="Badge color",
                max_length=16,
            ),
        ),
    ]
