# Generated by Django 4.2.14 on 2024-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0004_officer_faculty_advisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="email",
            field=models.EmailField(
                default="email@virginia.edu",
                help_text="UVA email address",
                max_length=254,
            ),
            preserve_default=False,
        ),
    ]
