# Generated by Django 4.2.14 on 2024-08-31 02:33

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0004_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officer",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="officer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="officer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="officer",
            name="image",
        ),
        migrations.RemoveField(
            model_name="officer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="officer",
            name="user",
            field=annoying.fields.AutoOneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="User's biography (Markdown is supported)"
            ),
        ),
    ]
