# Generated by Django 4.2.14 on 2024-07-28 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0005_officer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="officer",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Officer's biography (Markdown is supported)"
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="email",
            field=models.EmailField(
                help_text="UVA email address",
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(
                        allowlist=["virginia.edu"],
                        message="Enter a valid UVA email address",
                    )
                ],
            ),
        ),
    ]
