# Generated by Django 4.2.14 on 2024-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0006_alter_event_description_alter_event_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="email",
            field=models.EmailField(help_text="UVA email address", max_length=254),
        ),
    ]
