# Generated by Django 4.2.14 on 2024-08-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0006_alter_user_badges_alter_user_events_attended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(blank=True, to="acm_website.badge"),
        ),
        migrations.AlterField(
            model_name="user",
            name="events_attended",
            field=models.ManyToManyField(blank=True, to="acm_website.event"),
        ),
    ]
