# Generated by Django 4.2.14 on 2024-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0008_carouselimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Optional sort order of image"
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="An optional extended caption for the image",
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="image",
            field=models.ImageField(
                help_text="An image for the home page carousel", upload_to="carousel/"
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="label",
            field=models.CharField(help_text="A label for the image", max_length=30),
        ),
    ]
