# Generated by Django 4.2.14 on 2024-10-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0008_user_hide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="officer",
            unique_together={("year", "user")},
        ),
    ]
