# Generated by Django 4.2.14 on 2024-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0009_alter_officer_user_alter_officer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True, help_text="Badge description"),
        ),
    ]
