# Generated by Django 4.2.14 on 2024-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0010_alter_event_description_alter_event_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="acm.png",
                help_text="Optional event image",
                upload_to="events/",
            ),
        ),
    ]
