# Generated by Django 4.2.14 on 2024-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0011_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Optional event image", upload_to="events/"
            ),
        ),
    ]
