# Generated by Django 4.2.14 on 2024-07-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0012_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                default="acm.png", help_text="Event image", upload_to="events/"
            ),
        ),
    ]
