# Generated by Django 4.2.14 on 2024-07-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0013_alter_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HSPCContest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2024, unique=True)),
                (
                    "problem_set",
                    models.FileField(
                        help_text="Problem set PDF", upload_to="hspc/problems/"
                    ),
                ),
                (
                    "judge_data",
                    models.FileField(
                        help_text="Judge input/output ZIP", upload_to="hspc/judge/"
                    ),
                ),
            ],
        ),
    ]
