# Generated by Django 4.2.14 on 2024-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0014_hspccontest"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavBarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="Link to page", unique=True)),
                (
                    "label",
                    models.CharField(help_text="A label for the link", max_length=30),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Optional sort order of link"
                    ),
                ),
            ],
        ),
    ]
