# Generated by Django 4.2.14 on 2024-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0015_navbarlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbarlink",
            name="url",
            field=models.CharField(
                help_text="Link to page", max_length=150, unique=True
            ),
        ),
    ]
