# Generated by Django 4.2.14 on 2024-08-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acm_website", "0016_alter_navbarlink_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carouselimage",
            options={
                "verbose_name": "Carousel image",
                "verbose_name_plural": "Carousel images",
            },
        ),
        migrations.AlterModelOptions(
            name="hspccontest",
            options={
                "verbose_name": "HSPC contest",
                "verbose_name_plural": "HSPC contests",
            },
        ),
        migrations.AlterModelOptions(
            name="navbarlink",
            options={
                "verbose_name": "Navbar link",
                "verbose_name_plural": "Navbar links",
            },
        ),
    ]
